version: "3"

services:
    bvdl.nguyenhongquang.edu.vn:
        restart: always
        build:
            context: ./server
            dockerfile: Dockerfile
        image: neogruh/ehospital-server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules 
        networks:
            - app-test
    frontend:
        stdin_open: true
        restart: always
        build:
            context: ./client
            dockerfile: Dockerfile
        image: neogruh/ehospital-client
        ports:
            - "80:3000"
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
        links:
            - backend
        networks:
            - app-test

networks:
    app-test:
        driver: bridge
        

